### ISSUE TITLE
System lock upon setting network.target

### ISSUE THREAD

**Issue by michaelmcdonald** [fedberry/fedberry#12]
I installed the 23.2 (xfce) test image on a 64G Samsung MicroSD and was using it in my RPi3. Everything was going well until I set the default target to network.target and rebooted the RPi3. At that point it started the shutdown process and then went to a black screen showing only the four raspberry icons.

Any additional information you need, just let me know!

**Comment by agrez** [comment]
This would be expected behaviour. You set your default target to network.target and once the target is reached (which is early on in the boot process), it won't go beyond that point. The system does not actually lock up (remove the 'quiet' option from /boot/cmdline.txt to see boot messages), it just reaches the network.target and stops. You never go beyond this target so you will never get to multi-user.target or graphical.target, therefore you don't get login prompts.
