### ISSUE TITLE
Kernel compilation issue

### ISSUE THREAD

**Issue by guilhermegm** [fedberry/fedberry#13]
I just downloaded the latest fedberry (Fedora-23-remix-rpi2-xfce-1-raw.xz) and I'm tryng to build the kernel.

But I'm getting the follow error:
[root@localhost 4.2.8-401.9bc62df.bcm2709.fc23.armv7hl]# make
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
make[1]: *** No rule to make target 'arch/arm/tools/gen-mach-types', needed by 'include/generated/mach-types.h'.  Pare.
arch/arm/Makefile:315: recipe for target 'archprepare' failed
make: *** [archprepare] Error 2

fedberry:
uname -r 4.2.5-400.50acac3.bcm2709.fc23.armv7hl

well I'm using the kernel source 4.2.8 (http://download.fedberry.org/releases/23/packages/stable/RPMS/)

What m'I missing?

Where I can find all the source for 4.2.5... kernel?

I need to compile the kernel to install a driver.

Thanks!!

**Comment by agrez** [comment]
Hi guilhermegm.
Since we are Fedora remix, we build our kernels in a similar way to fedora. Like fedora, we do not provide a pre-prepared full kernel source tree for you to build from (only headers in the kernel-devel rpm). If you want to build a custom kernel from our sources, you will have to build from all sources provided in the kernel src.rpm located here:

http://download.fedberry.org/releases/23/packages/stable/SRPMS/

You might also want to take a look at the following wiki entry: 
https://fedoraproject.org/wiki/Building_a_custom_kernel#Building_a_Kernel_from_the_source_RPM

If you are not able to modify our kernel src.rpm to suit your needs, then maybe building custom kernel straight from raspberry sources might be easier for you. Follow this guide.

https://www.raspberrypi.org/documentation/linux/kernel/building.md

Regards
Vaughan

**Comment by guilhermegm** [comment]
@agrez 
Thank you very much, it helped me a lot
