### ISSUE TITLE
Pi0 usb slave

### ISSUE THREAD

**Issue by Gormartsen** [fedberry/fedberry#14]
There is some docs and info how to make zero like sub device to computer :
- keyboard
  -mouse
- usb network
  Etc

http://blog.gbaman.info/?p=699

**Comment by mrjoshuap** [comment]
It should be noted that for non-zero use cases that some serious (de-)soldering needs to be employed to get the zero-like behavior for the g_* devices on the PI2/3 systems due to the USB hub used on the non-zero systems.  I have successfully performed this operation, but it was not a trivial task.  On the PI Zero boards it was trivial because of the OTG (On The Go) USB nature built in; a standard USB cable connected to the correct port performed the task admirably.
