### ISSUE TITLE
Does fedberry support 64bit?

### ISSUE THREAD

**Issue by XiYuan68** [fedberry/fedberry#41]
Hi, first of all thank you for developing the OS, and I have a questions as the title. I've heard that 64bit OS has significant performance improvement on Pi3 compared to 32bit OS, and fedora28 supports 64bit on Pi3, so just curious about that.

**Comment by agrez** [comment]
No, we don't produce any 64bit images, as mainly I don't have time but also due to the fact that RPi userland libs are not 64 bit compatible, so you lose some hardware support. As for performance improvements, I haven't looked into this for quite a while now but at the time, there didn't seem to be much of a compelling case to go 64 bit, as performance improvements were only seen in certain situations, such as crypto algorithms and in other corner cases. Yep, Fedora has had a arm 64bit releases out for a while now and if they ever end up faster than Fedberry my interest in 64bit might be tweaked ;-)

**Comment by XiYuan68** [comment]
I see... Thanks for replying!
